on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    steps:
    - uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    - uses: actions/upload-artifact@v3
      with:
        name: Build
        path: dist
    
  
